export const theme = {
  colors: {
    primary: '#1A1A1A',
    accent: '#F97316',
    accentHover: '#EA580C',
    accentLight: 'rgba(249, 115, 22, 0.1)',
    background: '#FFF2DB',
    surface: '#FFFFFF',
    textPrimary: '#1A1A1A',
    textSecondary: '#4B5563',
    textTertiary: '#9CA3AF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    success: '#22C55E',
    successLight: '#DCFCE7',
    error: '#EF4444',
    errorLight: '#FEE2E2',
    warning: '#F59E0B',
    warningLight: '#FEF3C7',
    info: '#3B82F6',
    infoLight: '#DBEAFE',
    expertPrimary: '#6D28D9',
    expertPrimaryLight: '#EDE9FE',
    expertPrimaryMuted: 'rgba(109, 40, 217, 0.12)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    xxl: 24,
    pill: 9999,
  },
  typography: {
    h1: { fontSize: 32, fontWeight: 'normal', fontFamily: 'Lufga-Bold' },
    h2: { fontSize: 24, fontWeight: 'normal', fontFamily: 'Lufga-Bold' },
    h3: { fontSize: 20, fontWeight: 'normal', fontFamily: 'Lufga-Bold' },
    body: { fontSize: 16, fontWeight: 'normal', fontFamily: 'Lufga-Bold' },
    bodyMedium: { fontSize: 16, fontWeight: 'normal', fontFamily: 'Lufga-Bold' },
    bodyBold: { fontSize: 16, fontWeight: 'normal', fontFamily: 'Lufga-Bold' },
    caption: { fontSize: 14, fontWeight: 'normal', fontFamily: 'Lufga-Bold' },
    small: { fontSize: 12, fontWeight: 'normal', fontFamily: 'Lufga-Bold' },
  }
};
